import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {stageDir} from 'red/cli';
import type {Opts} from 'red/workflow';
import {orchestrate,plan_deployment,read_deployment,validate,backend_plan,source_cidrs} from 'colors-compute-red';
export const topology=[{count:1}];
export function requirements(opts:Opts){const ssh=source_cidrs(opts,'ssh-sources','netbird-ssh-sources'),http=source_cidrs(opts,'http-sources','netbird-http-sources');if(!ssh.length)throw new Error("SSH source list must not be empty");const stun=source_cidrs(opts,"stun-sources","netbird-stun-sources");return {single_host:true,ipv6:false,security:{egress:'all',private_filter:false,ingress:[{id:'ssh',protocol:'tcp',from_port:22,to_port:22,sources:ssh},...[80,443].map(port=>({id:'web-'+port,protocol:'tcp',from_port:port,to_port:port,sources:http})),...(stun.length?[{id:"stun",protocol:"udp",from_port:opts["netbird-stun-port"],to_port:opts["netbird-stun-port"],sources:stun}]:[])]},legacy_state_keys:[opts.profile+'/netbird-infrastructure.tfstate']};}
export function errors(opts:Opts):string[]{try{const errors=validate(opts);if(errors.length)return errors;plan_deployment(opts,topology,requirements(opts));return [];}catch{return ['invalid singleton compute requirements'];}}
function attach(opts:Opts,result:any):Opts{if(!['planned','ready','present','destroyed'].includes(result.status))return {...opts,'red/exit':1,'red/err':result.errors?.join('\n')||'compute lifecycle refused'};if(result.status==='destroyed')return {...opts,'red/exit':0,'netbird/already-destroyed':true};const node=result.cluster.nodes.find((n:any)=>n.node_id===result.cluster.entry_node_id);return {...opts,...node,'red/exit':0,'colors-compute/cluster':result.cluster,'colors-compute/key':result.key,'ssh-private-key-path':result.key?.private_key_path??node.ssh_identity_file};}
function sorted(value:any):any{return Array.isArray(value)?value.map(sorted):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,sorted(value[k])])):value;}
export async function infrastructureStep(opts:Opts):Promise<Opts>{const planning=opts['red/event']==='build'||opts['red/dry-run'],result=planning?plan_deployment(opts,topology,requirements(opts)):await orchestrate(opts,topology,requirements(opts));if(planning){const root=stageDir(opts,'compute'),stacks:[string,Record<string,any>][]=[['shared',result.documents.shared],...Object.entries(result.documents.nodes).map(([id,docs])=>['nodes/'+id,docs] as [string,Record<string,any>])];for(const [suffix,docs]of stacks){const dir=join(root,suffix),key=suffix==='shared'?result.state_keys.shared:result.state_keys.nodes[suffix.split('/')[1]!];mkdirSync(dir,{recursive:true});for(const [name,document]of Object.entries({...docs,'backend.tf.json':backend_plan(opts,key).config}))writeFileSync(join(dir,name),JSON.stringify(sorted(document),null,2)+'\n');}}return attach(opts,result);}
export async function loadStep(opts:Opts):Promise<Opts>{if(opts['red/dry-run'])return opts;return attach(opts,await read_deployment(opts,undefined,undefined,requirements(opts)));}
